name: Image build and Test, Deploy to Amazon ECS
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: tottoko_api
  ECS_SERVICE: tottoko-prod-service
  ECS_CLUSTER: tottoko-prod-cluster
  ECS_TASK_DEFINITION: task-definition.json
  CONTAINER_NAME: tottoko-api

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    environment: production
    outputs:
      docker-image: ${{ steps.build-image.outputs.image }}
      docker-image-name: ${{ steps.build-image.outputs.image_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
        echo "::set-output name=image::${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
        image_name="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
        echo "::set-output name=image_name::${image_name}"

  test:
    name: Test image
    needs: build
    runs-on: ubuntu-latest
    env:
      TARGET_IMAGE: ${{ needs.build.outputs.docker-image-name }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build test environment
      run: |
        docker compose -f docker-compose.ci.yml up db -d
        sleep 15 # DB起動待ち
        docker compose -f docker-compose.ci.yml up api
        docker compose -f docker-compose.ci.yml run api rails db:create
        docker compose -f docker-compose.ci.yml run api rails db:migrate

    - name: Test image
      run: |
        docker compose -f docker-compose.ci.yml run api bundle exec rspec

  deploy:
    name: Deploy to Amazon ECS
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - name: Push image to Amazon ECR
      run: |
        docker push ${{ needs.build.outputs.docker-image }}
        
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ needs.build.outputs.docker-image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: false # false(デプロイの結果を待たない）
